修正
OnoueUkyo/TutorialApp pull request #2
Opened 2023-07-27 07:04 UTC by OnoueUkyo

レビューお願いします

2023-07-27 07:39 UTC, ryu-joe requested changes

2023-07-27 07:39 UTC, ryu-joe commented on ContentView/FirstChildView.swift
> +}
このファイルは何をするためのViewですか？

2023-07-27 07:39 UTC, ryu-joe commented on ContentView/FirstView.swift
> +                            }.font(.system(size:20))
子要素としてまとめたほうがいいです👌

2023-07-27 07:39 UTC, ryu-joe commented on ContentView/FirstView.swift
>      }
ここの変数は何をする変数ですか？

2023-07-27 07:39 UTC, ryu-joe commented on ContentView/SecondView.swift
> +                                if (index==ac.count-1){
```suggestion
//ここの括弧はおそらくつけなくても大丈夫です
                                if index==ac.count-1{
```

2023-07-27 07:39 UTC, ryu-joe commented on ContentView/SecondView.swift
>          NavigationView{
多分このNavigationViewはつけなくても正常に動作すると思います

2023-07-27 07:48 UTC, OnoueUkyo commented on ContentView/FirstChildView.swift
> +}
FirstViewの行数が多くなったため分けようと作成したViewですが、まだ使用していません。

2023-07-27 07:49 UTC, OnoueUkyo commented on ContentView/FirstView.swift
>      }
すみません消し忘れました。

2023-07-27 09:09 UTC, ryu-joe commented on ContentView/SecondView.swift
>          NavigationView{
間違えでしたごめんなさい。

2023-07-31 00:26 UTC, ryu-joe requested changes

2023-07-31 00:26 UTC, ryu-joe commented on ContentView/Components/ButtonFun.swift
> +    @State var buttonText = "フォロー"
//これから見る人も加味した上でこのbuttonTextとがとる文字を一覧でコメントとして表示してもいいかも（俺はちなみにこれできてません）

2023-07-31 00:26 UTC, ryu-joe commented on ContentView/ContentView.swift
>              }
何をするタブなのかかなりわかりやすくなりました。
良い👏

2023-07-31 00:26 UTC, ryu-joe commented on ContentView/NoticeView.swift
> +                    Divider().padding(.top,20)
```suggestion
                 HStack{
                        Text("今日")
                            .padding(EdgeInsets(
                                top: 15,
                                leading: 20,
                                bottom: 10,
                                trailing: 0
                            ))
                        Spacer()
                    }
                    HStack{
                        Circle()
                            .frame(height:40)
                            .foregroundColor(.white)
                            .overlay(
                                Circle().stroke())
                        Text("Onoueがあなたをフォローしました。")
                            .frame(
                                maxWidth:.infinity,
                                alignment: .leading
                            )
                        ButtonFun()
                            .padding(.trailing,15)
                    }.padding(.leading,15)
                    Divider()
```

2023-07-31 00:26 UTC, ryu-joe commented on ContentView/NoticeView.swift
> +                    Divider().padding(.top,20)
こっちの方がいいかな

2023-07-31 00:26 UTC, ryu-joe commented on ContentView/NoticeView.swift
> +                    Divider().padding(.top,20)
ButtonFunのpaddingも消してる(消したほうが汎用性が高いと思う)

2023-07-31 00:59 UTC, ryu-joe approved these changes

2023-07-31 00:59 UTC, merged